### ISSUE TITLE
Logowanie akcji

### ISSUE THREAD

**Issue by kpodsiad** [JanTry/IO_TEAM_B_20-21#22]
Jako istotna akcja chciałabym się pojawić w logach systemu żeby ktoś mnie zauważył

**Comment by szarbartosz** [comment]
kryteria akceptacji:
- [ ] stworzenie kolekcji (np. logs / student activity)
- [ ] zapisywanie w niej informacji: dołączenie/opuszczenie spotkania przez studenta (godzina, id studenta, id sesji)
- [ ] wystawienie endpointu zwracjącego listę krotek aktywności w danej sesji: (student, godzina dołączenia, godzina opuszczenia)
